<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12" />
    <!-- Replaced by own components in phase 4. -->
    <PackageVersion Include="MudBlazor" Version="6.19.1" />
    <PackageVersion Include="PublishSPAforGitHubPages.Build" Version="3.0.3" />
  </ItemGroup>

</Project>
